/*
 * This file is generated by jOOQ.
*/
package net.comerge.codingday.backend.database.models.backend.tables;


import java.util.Arrays;
import java.util.List;
import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;

import net.comerge.codingday.backend.database.models.backend.Backend;
import net.comerge.codingday.backend.database.models.backend.Keys;
import net.comerge.codingday.backend.database.models.backend.tables.records.MapUserToTeamRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MapUserToTeam extends TableImpl<MapUserToTeamRecord> {

    private static final long serialVersionUID = 728972039;

    /**
     * The reference instance of <code>BACKEND.MAP_USER_TO_TEAM</code>
     */
    public static final MapUserToTeam MAP_USER_TO_TEAM = new MapUserToTeam();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MapUserToTeamRecord> getRecordType() {
        return MapUserToTeamRecord.class;
    }

    /**
     * The column <code>BACKEND.MAP_USER_TO_TEAM.USER</code>.
     */
    public final TableField<MapUserToTeamRecord, Long> USER = createField("USER", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>BACKEND.MAP_USER_TO_TEAM.TEAM</code>.
     */
    public final TableField<MapUserToTeamRecord, Long> TEAM = createField("TEAM", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>BACKEND.MAP_USER_TO_TEAM</code> table reference
     */
    public MapUserToTeam() {
        this("MAP_USER_TO_TEAM", null);
    }

    /**
     * Create an aliased <code>BACKEND.MAP_USER_TO_TEAM</code> table reference
     */
    public MapUserToTeam(String alias) {
        this(alias, MAP_USER_TO_TEAM);
    }

    private MapUserToTeam(String alias, Table<MapUserToTeamRecord> aliased) {
        this(alias, aliased, null);
    }

    private MapUserToTeam(String alias, Table<MapUserToTeamRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Backend.BACKEND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<MapUserToTeamRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MapUserToTeamRecord, ?>>asList(Keys.CONSTRAINT_5, Keys.CONSTRAINT_5F);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MapUserToTeam as(String alias) {
        return new MapUserToTeam(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MapUserToTeam rename(String name) {
        return new MapUserToTeam(name, null);
    }
}
