/*
 * This file is generated by jOOQ.
*/
package net.comerge.codingday.backend.database.models.backend.tables;


import java.util.Arrays;
import java.util.List;
import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import net.comerge.codingday.backend.database.models.backend.Backend;
import net.comerge.codingday.backend.database.models.backend.Keys;
import net.comerge.codingday.backend.database.models.backend.tables.records.TeamRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Team extends TableImpl<TeamRecord> {

    private static final long serialVersionUID = -1837287138;

    /**
     * The reference instance of <code>BACKEND.TEAM</code>
     */
    public static final Team TEAM = new Team();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeamRecord> getRecordType() {
        return TeamRecord.class;
    }

    /**
     * The column <code>BACKEND.TEAM.ID</code>.
     */
    public final TableField<TeamRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("(NEXT VALUE FOR BACKEND.SYSTEM_SEQUENCE_D9180AD8_8353_48D5_9008_4684EF062B7D)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>BACKEND.TEAM.NAME</code>.
     */
    public final TableField<TeamRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>BACKEND.TEAM.DESCRIPTION</code>.
     */
    public final TableField<TeamRecord, String> DESCRIPTION = createField("DESCRIPTION", org.jooq.impl.SQLDataType.VARCHAR.length(1000).nullable(false), this, "");

    /**
     * Create a <code>BACKEND.TEAM</code> table reference
     */
    public Team() {
        this("TEAM", null);
    }

    /**
     * Create an aliased <code>BACKEND.TEAM</code> table reference
     */
    public Team(String alias) {
        this(alias, TEAM);
    }

    private Team(String alias, Table<TeamRecord> aliased) {
        this(alias, aliased, null);
    }

    private Team(String alias, Table<TeamRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Backend.BACKEND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TeamRecord, Long> getIdentity() {
        return Keys.IDENTITY_TEAM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TeamRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_27;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TeamRecord>> getKeys() {
        return Arrays.<UniqueKey<TeamRecord>>asList(Keys.CONSTRAINT_27);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Team as(String alias) {
        return new Team(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Team rename(String name) {
        return new Team(name, null);
    }
}
