server:
    servlet:
        context-path: /v1
spring:
    datasource:
        url: jdbc:h2:file:~/backend
        username: codingday
        password: ''
        driver-class-name: org.h2.Driver
    h2:
        console:
            enabled: true
            path: /h2
    main:
        allow-bean-definition-overriding: true

