/*
 * This file is generated by jOOQ.
*/
package net.comerge.codingday.backend.database.models.backend;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import net.comerge.codingday.backend.database.models.DefaultCatalog;
import net.comerge.codingday.backend.database.models.backend.tables.MapUserToTeam;
import net.comerge.codingday.backend.database.models.backend.tables.News;
import net.comerge.codingday.backend.database.models.backend.tables.Team;
import net.comerge.codingday.backend.database.models.backend.tables.User;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Backend extends SchemaImpl {

    private static final long serialVersionUID = -959562077;

    /**
     * The reference instance of <code>BACKEND</code>
     */
    public static final Backend BACKEND = new Backend();

    /**
     * The table <code>BACKEND.MAP_USER_TO_TEAM</code>.
     */
    public final MapUserToTeam MAP_USER_TO_TEAM = net.comerge.codingday.backend.database.models.backend.tables.MapUserToTeam.MAP_USER_TO_TEAM;

    /**
     * The table <code>BACKEND.NEWS</code>.
     */
    public final News NEWS = net.comerge.codingday.backend.database.models.backend.tables.News.NEWS;

    /**
     * The table <code>BACKEND.TEAM</code>.
     */
    public final Team TEAM = net.comerge.codingday.backend.database.models.backend.tables.Team.TEAM;

    /**
     * The table <code>BACKEND.USER</code>.
     */
    public final User USER = net.comerge.codingday.backend.database.models.backend.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Backend() {
        super("BACKEND", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.SYSTEM_SEQUENCE_28BB8583_2CA5_4C42_B569_30893648F344,
            Sequences.SYSTEM_SEQUENCE_901E7580_EA03_4FA7_965F_58AEA7E3E92B,
            Sequences.SYSTEM_SEQUENCE_D9180AD8_8353_48D5_9008_4684EF062B7D);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            MapUserToTeam.MAP_USER_TO_TEAM,
            News.NEWS,
            Team.TEAM,
            User.USER);
    }
}
