/*
 * This file is generated by jOOQ.
*/
package net.comerge.codingday.backend.database.models.backend;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in BACKEND
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>BACKEND.SYSTEM_SEQUENCE_28BB8583_2CA5_4C42_B569_30893648F344</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_28BB8583_2CA5_4C42_B569_30893648F344 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_28BB8583_2CA5_4C42_B569_30893648F344", Backend.BACKEND, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>BACKEND.SYSTEM_SEQUENCE_901E7580_EA03_4FA7_965F_58AEA7E3E92B</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_901E7580_EA03_4FA7_965F_58AEA7E3E92B = new SequenceImpl<Long>("SYSTEM_SEQUENCE_901E7580_EA03_4FA7_965F_58AEA7E3E92B", Backend.BACKEND, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>BACKEND.SYSTEM_SEQUENCE_D9180AD8_8353_48D5_9008_4684EF062B7D</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_D9180AD8_8353_48D5_9008_4684EF062B7D = new SequenceImpl<Long>("SYSTEM_SEQUENCE_D9180AD8_8353_48D5_9008_4684EF062B7D", Backend.BACKEND, org.jooq.impl.SQLDataType.BIGINT);
}
