/*
 * This file is generated by jOOQ.
*/
package net.comerge.codingday.backend.database.models.backend;


import javax.annotation.Generated;

import net.comerge.codingday.backend.database.models.backend.tables.MapUserToTeam;
import net.comerge.codingday.backend.database.models.backend.tables.News;
import net.comerge.codingday.backend.database.models.backend.tables.Team;
import net.comerge.codingday.backend.database.models.backend.tables.User;


/**
 * Convenience access to all tables in BACKEND
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>BACKEND.MAP_USER_TO_TEAM</code>.
     */
    public static final MapUserToTeam MAP_USER_TO_TEAM = net.comerge.codingday.backend.database.models.backend.tables.MapUserToTeam.MAP_USER_TO_TEAM;

    /**
     * The table <code>BACKEND.NEWS</code>.
     */
    public static final News NEWS = net.comerge.codingday.backend.database.models.backend.tables.News.NEWS;

    /**
     * The table <code>BACKEND.TEAM</code>.
     */
    public static final Team TEAM = net.comerge.codingday.backend.database.models.backend.tables.Team.TEAM;

    /**
     * The table <code>BACKEND.USER</code>.
     */
    public static final User USER = net.comerge.codingday.backend.database.models.backend.tables.User.USER;
}
